USE [master]
GO

/****** Object:  Database [Population]    Script Date: 25.07.2023 18:43:33 ******/
CREATE DATABASE [Population]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Population', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER2\MSSQL\DATA\Population.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Population_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER2\MSSQL\DATA\Population_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Population].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Population] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Population] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Population] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Population] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Population] SET ARITHABORT OFF 
GO

ALTER DATABASE [Population] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Population] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Population] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Population] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Population] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Population] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Population] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Population] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Population] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Population] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Population] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Population] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Population] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Population] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Population] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Population] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Population] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Population] SET RECOVERY FULL 
GO

ALTER DATABASE [Population] SET  MULTI_USER 
GO

ALTER DATABASE [Population] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Population] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Population] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Population] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Population] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Population] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Population] SET QUERY_STORE = ON
GO

ALTER DATABASE [Population] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [Population] SET  READ_WRITE 
GO


